DROP TABLE IF EXISTS redactor_content;
DROP TABLE IF EXISTS item_content;
DROP TABLE IF EXISTS property_tag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS duration_matter;
DROP TABLE IF EXISTS date_matter;
DROP TABLE IF EXISTS digital_matter;
DROP TABLE IF EXISTS string_matter;
DROP TABLE IF EXISTS redactor;
DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS rubric_item;
DROP TABLE IF EXISTS rubric_property;
DROP TABLE IF EXISTS rubric_element_tree;
DROP TABLE IF EXISTS property;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS rubric;
DROP TABLE IF EXISTS element_tree;
--DROP DATABASE information_catalog;